#!/bin/bash

filename=$(date +'%Y-%m-%d-%H.%M.%S').png
filepath=$(cat $HOME/.config/screenshot-utils/screenshot-path)
copypath=$(cat $HOME/.config/screenshot-utils/copy-path)

if [ $copypath ]
then
    echo $filepath/$filename | wl-copy
fi

grim -g "$(slurp)" - | tee $filepath/$filename | wl-copy

