#!/bin/bash

filename=$(date +'%Y-%m-%d-%H.%M.%S').png
filepath=$(cat $HOME/.config/screenshot-utils/screenshot-path)
copypath=$(cat $HOME/.config/screenshot-utils/copy-path)

if [ $copypath == "TRUE" ]
then
    echo $filepath/$filename | wl-copy
fi

grim -g "$(swaymsg -t get_tree | jq -j '.. | select(.type?) | select(.focused).rect | "\(.x),\(.y) \(.width)x\(.height)"')" - | 
	tee $filepath/$filename | wl-copy

